ALTER TABLE reminders ADD COLUMN period_type TEXT NOT NULL DEFAULT '';
ALTER TABLE reminders ADD COLUMN period_value INTEGER NOT NULL DEFAULT 0;
ALTER TABLE reminders ADD COLUMN period_desc TEXT NOT NULL DEFAULT '';
ALTER TABLE reminders ADD COLUMN next_remind_at INTEGER NOT NULL DEFAULT 0;